// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://mmuhtwhyldvvgcclobuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tdWh0d2h5bGR2dmdjY2xvYnV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NjY2MDcsImV4cCI6MjA3MzQ0MjYwN30.CLcZBrdYv0U_ug_YB7nFnv4F8FjhF-zvj2Uc3MGNyWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);